TRUNCATE cart CASCADE;
TRUNCATE cart_product CASCADE;
TRUNCATE category CASCADE;
TRUNCATE category_product CASCADE;
TRUNCATE image CASCADE;
TRUNCATE product CASCADE;
INSERT INTO image VALUES (0, NULL) ON CONFLICT DO NOTHING;