name: Release Workflow
on:
  push:
    tags:
      - '*'
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy release
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install the dependencies
        working-directory: .
        run: mvn clean package
      - name: display
        run: ls target
      - name: display
        run: ls target/quarkus-app
      - name: Create release
        uses: Roang-zero1/github-create-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create GitHub release
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args: |
            target/quarkus-app/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
