on:
  push:
    tags:
      - '*'
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy release
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install the dependencies
        working-directory: .
        run: mvn clean install -DskipTests=true
      - name: Run the tests
        run: mvn test
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Release
        uses: softprops/action-gh-release@91409e712cf565ce9eff10c87a8d1b11b81757ae
        with:
          # Identify if this is a pre release by checking if the tag name contains -rc, -b, -a
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-b') || contains(github.ref, '-a') }}
          if: startsWith(github.ref, 'refs/tags/')
          files: target/quarkus-app/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
